version: '2'
services:
  glassfish:
    build: .
    ports:
      - "8080:8080"
  db:
    image: mariadb:10.0
    environment:
      MYSQL_ROOT_PASSWORD : coucou
      MYSQL_DATABASE : coursesdb
    ports :
      - 3306:3306
