/**
 * Author:  clement
 * Created: 23 janv. 2017
 */

/*INSERT INTO APP.COURSESUSER (ID, CREATED, EMAIL, LASTCONNECTION, PASSWORD, USERNAME) VALUES (1, 0, 'mail@mail.fr', 0, 'dGVzdA==', 'admin')*/
INSERT INTO APP.COURSESUSER (ID, CREATED, EMAIL, LASTCONNECTION, PASSWORD, USERNAME) VALUES (1, null, 'mail@mail.fr', null, 'maxime', 'Maxime')
INSERT INTO APP.COURSES (IDCOURSES, DETAILS, LABEL, RANK) VALUES (1, '# test', 'Cours test 1', 0)
INSERT INTO APP.COURSES (IDCOURSES, DETAILS, LABEL, RANK) VALUES (2, '# test1', 'Cours test 1', 0)
INSERT INTO APP.COURSES (IDCOURSES, DETAILS, LABEL, RANK) VALUES (3, '# test2', 'Cours test 2', 0)
INSERT INTO APP.COURSES (IDCOURSES, DETAILS, LABEL, RANK) VALUES (4, '# test3', 'Cours test 3', 0)
INSERT INTO APP.QUESTION (IDQUESTION, IDCOURSES, QUESTIONTEXT) VALUES (1, 1, 'What s the most butiful things you ever seen in your life ?')
INSERT INTO APP.QUESTION (IDQUESTION, IDCOURSES, QUESTIONTEXT) VALUES (2, 1, 'Tuhpuhduhcuh ?')
INSERT INTO APP.QUESTION (IDQUESTION, IDCOURSES, QUESTIONTEXT) VALUES (1, 2, 'What s the most butiful things you ever seen in your life ?')
INSERT INTO APP.QUESTION (IDQUESTION, IDCOURSES, QUESTIONTEXT) VALUES (2, 1, 'What s the most butiful things you ever seen in your life ?')
INSERT INTO APP.RESPONSES (IDRESPONSE, IDQUESTION, RESPONSETEXT, ISTRUE) VALUES (1, 1, 'Watermelon', 1)
INSERT INTO APP.RESPONSES (IDRESPONSE, IDQUESTION, RESPONSETEXT, ISTRUE) VALUES (2, 1, 'Banana', 0)
INSERT INTO APP.RESPONSES (IDRESPONSE, IDQUESTION, RESPONSETEXT, ISTRUE) VALUES (3, 1, 'Potato', 0)
INSERT INTO APP.RESPONSES (IDRESPONSE, IDQUESTION, RESPONSETEXT, ISTRUE) VALUES (1, 2, 'yes', 0)
INSERT INTO APP.RESPONSES (IDRESPONSE, IDQUESTION, RESPONSETEXT, ISTRUE) VALUES (2, 1, 'non', 1)